apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-creds
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgBb5be48kN0NLVemb7VGo0NlWsUB98BncmmhP9H66en3KWSvr18yzF64cXRGLpheUSBrgxRs25MxDfGnneHW8wFbW8/1C+t/StJcHTUe2IudvlD4m2Lee5HALsBK3qbvVmi/Xwg5PJ8ztbWMju4sAtsVtMoNvRReu/kJZdHln8X3mNFZZgQQY0fWYQVZ9qTfp3uD5nObfu8avjKV+J4vY/A9dt5tao1qqDmifh2AMNDbZvIsOLkjoTEVwqLY//1t2Wki0LE08I2hieiDyAzdmLo/uePTAbqpIe/ajTLC01WracbLNFumTPha807lwVwBeAOXCkBhJQS8O+Ii2lw77XWi+EPMtSC0WJcM9T5qspNBbQYP2nmmhoF4ymuVoQ+c79K9a3NK+rrrWZ9rqPef8L6OufU93YoQsQTy7PUq1n7bl+Ed6ohyw68g5yGtl+Sd1NEQF6Nw7gOE8h1KfhirbOGN9sNnU/EJgeSQEFOdGiZDu1kUoiyd3ZxYmZznf4nxDD+l8W9VxUPw+XdVgtVz2BqW09/wkvJj2CvRXiVqP8hJHxsASRcXprdrxvby3PE62z3ahXrqq3KYEGDgZl6EE43nlDw/qp81kKr2PdApR2rsL3wPox0pHTKXxtGF4wyjyuw+7f3ezvN1m1kWc59YOIGF+PlDDJ2leKUIzVArJuQTo3dP/J8QVX5oKM0shNWpz9JCX3zg7sO/Zj/WNqxTAlkaM7G9NZpYV6b2P5R9AEt6jUuxYdxp2aKT1HI0azJm7QZd8ShBI28tTuPy6yUw4SY7dI3/d+akRtO1cu53Bt1j8bi05+2rl3qyupKgghPd080R5gkHowc5i9h1dkQgnuyF1wIu3o=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: aws-creds
      namespace: crossplane-system

